/**
 * @fileoverview gRPC-Web generated client stub for counter
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: proto/counter/counter.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.counter = require('./counter_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.counter.CounterServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.counter.CounterServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.counter.IncrementRequest,
 *   !proto.counter.CounterResponse>}
 */
const methodDescriptor_CounterService_IncrementCounter = new grpc.web.MethodDescriptor(
  '/counter.CounterService/IncrementCounter',
  grpc.web.MethodType.UNARY,
  proto.counter.IncrementRequest,
  proto.counter.CounterResponse,
  /**
   * @param {!proto.counter.IncrementRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.counter.CounterResponse.deserializeBinary
);


/**
 * @param {!proto.counter.IncrementRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.counter.CounterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.counter.CounterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.counter.CounterServiceClient.prototype.incrementCounter =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/counter.CounterService/IncrementCounter',
      request,
      metadata || {},
      methodDescriptor_CounterService_IncrementCounter,
      callback);
};


/**
 * @param {!proto.counter.IncrementRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.counter.CounterResponse>}
 *     Promise that resolves to the response
 */
proto.counter.CounterServicePromiseClient.prototype.incrementCounter =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/counter.CounterService/IncrementCounter',
      request,
      metadata || {},
      methodDescriptor_CounterService_IncrementCounter);
};


module.exports = proto.counter;

